stages:
  prepare:
    cmd: python src/prepare.py --config params.yaml
    deps:
      - data/zameen-updated.csv
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/house_data_cleaned.csv

  features:
    cmd: python src/features.py --config params.yaml
    deps:
      - data/house_data_cleaned.csv
      - src/features.py
    params:
      - features
    outs:
      - data/X_train.npy
      - data/X_test.npy
      - data/y_train.npy
      - data/y_test.npy
      - models/label_encoders.pkl
      - models/feature_names.pkl

  train:
    cmd: python src/train.py --config params.yaml
    deps:
      - data/X_train.npy
      - data/y_train.npy
      - src/train.py
    params:
      - train
    outs:
      - models/house_price_model.pkl

  evaluate:
    cmd: python src/evaluate.py --config params.yaml
    deps:
      - models/house_price_model.pkl
      - data/X_test.npy
      - data/y_test.npy
      - src/evaluate.py
    metrics:
      - metrics/eval.json:
          cache: false
